version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d # Mount the data directory
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: havesomefund@admin.com
      PGADMIN_DEFAULT_PASSWORD: havesomefund123
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  postgres-data:
